/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import dao.Database;
import dao.DatabaseTipo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.table.TableColumn;
import model.Pneu;
import model.TipoVeiculo;
import model.Veiculo;
import tablemodel.VeiculoTableModel;

/**
 *
 * @author Fernando
 */
public class Consulta extends javax.swing.JPanel {

    VeiculoTableModel tModel = new VeiculoTableModel();

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        initComponentsCustom();
    }

    private void initComponentsCustom() {
        formulario1.setVisible(false);
        configureVeiculoTableModel();
        configureTextFields();
    }

    private void configureTextFields() {
        this.tfPlaca.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent ce) {
                if (tfPlaca.getText().isEmpty()) {
                    tfCodPneu.setEnabled(true);
                } else {
                    tfCodPneu.setEnabled(false);
                }
            }

        });

        this.tfCodPneu.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent ce) {
                if (tfCodPneu.getText().isEmpty()) {
                    tfPlaca.setEnabled(true);
                } else {
                    tfPlaca.setEnabled(false);
                }
            }
        });
    }

    private void configureVeiculoTableModel() {

        veiculoTable.setModel(tModel);

        TableColumn statusColumn = veiculoTable.getColumnModel().getColumn(0);
        statusColumn.setHeaderValue("Placa");

        TableColumn posicao = veiculoTable.getColumnModel().getColumn(1);
        posicao.setHeaderValue("Marca");

        TableColumn estado = veiculoTable.getColumnModel().getColumn(2);
        estado.setHeaderValue("Modelo");

        veiculoTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    Veiculo v = tModel.getVeiculoAt(veiculoTable.rowAtPoint(me.getPoint()));
                    consultarViaList(v);
                }
            }
        });

        for (Veiculo v : Database.selectFullVeiculos()) {
            tModel.addVeiculo(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        tfCodPneu = new javax.swing.JTextField();
        panelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        veiculoTable = new javax.swing.JTable();
        btConsultar = new javax.swing.JButton();
        formulario1 = new Form.Formulario();

        jLabel1.setText("Placa:");

        jLabel2.setText("Codigo pneu:");

        tfPlaca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfPlacaInputMethodTextChanged(evt);
            }
        });
        tfPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPlacaKeyPressed(evt);
            }
        });

        tfCodPneu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodPneuKeyPressed(evt);
            }
        });

        panelConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visão geral de Registros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        veiculoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(veiculoTable);

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formulario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfCodPneu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btConsultar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar))
                .addGap(18, 18, 18)
                .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formulario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void consultarViaList(Veiculo v) {
        renderSelectedVeiculo(Database.selectVeiculo(v.getPlaca(), null));
    }

    private void consultar() {

        if (!tfCodPneu.getText().isEmpty() || !tfPlaca.getText().isEmpty()) {
            Veiculo v = Database.selectVeiculo(tfPlaca.getText(), tfCodPneu.getText());
            if (v.getPlaca() != null) {
                renderSelectedVeiculo(v);
                
            } else {
                String param = tfCodPneu.getText().isEmpty() ? tfPlaca.getText() : tfCodPneu.getText();
                String paramName = tfCodPneu.getText().isEmpty() ? "[Placa: " : "[Código Pneu: ";
                JOptionPane.showMessageDialog(this, "Veículo não encontrado com o parâmetro informado " + paramName + param + "]");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher um dos campos para executar a pesquisa !");
        }
    }

    private void renderSelectedVeiculo(Veiculo v) {

        formulario1.veicIdFromConsulta = v.getId();
        formulario1.getTfPlaca().setText(v.getPlaca());
        formulario1.getTfModelo().setText(v.getModelo());
        formulario1.getTfKm().setText(String.valueOf(v.getKm()));

        formulario1.getTfPeso().setText(String.valueOf(v.getPeso()));
        formulario1.getTfMarca().setText(v.getMarca());
        formulario1.getImagePanel1().carregaImagem(v.getImg());
        loadComboTipoVeiculo(DatabaseTipo.selecteTipo(v.getIdTipo()).getNome());
        formulario1.getTfAno().setText(v.getAno());

        for (Pneu p : v.getPneus()) {
            formulario1.insertPneuInTable(p);
        }

        panelConsulta.setVisible(false);
        formulario1.setVisible(true);
        formulario1.setHabilitarEdicaoVisible(true);
        formulario1.setComponentsEditable(false);
        formulario1.isEdicao = true;
        formulario1.loadIconComponent();

        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.pack();
        topFrame.setLocationRelativeTo(null);
    }

    private void loadComboTipoVeiculo(String nome) {

        TipoVeiculo item;
        for (int i = 0; i < formulario1.getComboTipo().getItemCount(); i++) {
            item = (TipoVeiculo) formulario1.getComboTipo().getItemAt(i);
            if (item.getNome().equals(nome)) {
                formulario1.getComboTipo().setSelectedIndex(i);
                break;
            }
        }
    }
    private void tfPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlacaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultar();
        }
    }//GEN-LAST:event_tfPlacaKeyPressed

    private void tfCodPneuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodPneuKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultar();
        }
    }//GEN-LAST:event_tfCodPneuKeyPressed

    private void tfPlacaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfPlacaInputMethodTextChanged
    }//GEN-LAST:event_tfPlacaInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private Form.Formulario formulario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JTextField tfCodPneu;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTable veiculoTable;
    // End of variables declaration//GEN-END:variables
}
