/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import dao.Database;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pneu;
import model.TipoVeiculo;

/**
 *
 * @author fobm
 */
public class PneuForm extends javax.swing.JFrame {

    static Formulario f = null;

    /**
     * Creates new form JFrame
     *
     * @param f
     */
    public PneuForm(Formulario f) {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.f = f;
        pack();
        setLocationRelativeTo(null);
        loadCombos((TipoVeiculo) f.getComboTipo().getSelectedItem());
    }

    private void loadCombos(TipoVeiculo t) {
        configureComboEixo(t);
        configureComboPosicaoPneu(t);
    }

    private void configureComboPosicaoPneu(TipoVeiculo t) {
        comboPosicao.setEnabled(false);
        comboPosicao.addItem("Selecione");

        if (t.getNome().equals("Veículo Passeio")) {
            comboPosicao.addItem("Pneu esquerdo");
            comboPosicao.addItem("Pneu direito");
            comboPosicao.addItem("Estepe");
            return;
        }
        if (t.getRodasPorEixo() == 2) {
            comboPosicao.addItem("Pneu esquerdo");
            comboPosicao.addItem("Pneu direito");
        }

        if (t.getRodasPorEixo() > 2) {
            comboPosicao.addItem("Pneu externo esquerdo");
            comboPosicao.addItem("Pneu externo direito");
            comboPosicao.addItem("Pneu interno direito");
            comboPosicao.addItem("Pneu interno esquerdo");

        }
        comboPosicao.addItem("Estepe");

    }

    private void configureComboEixo(TipoVeiculo t) {
        comboEixo.addItem("Selecione");

        if (t.getNome().equals("Veículo Passeio")) {
            labelEixo.setText("Orientação Pneu: ");
            comboEixo.addItem("Dianteiro");
            comboEixo.addItem("Traseiro");
            comboEixo.addItem("Estepe");

            return;
        }

        if (t.getNumeroEixos() == 2) {
            comboEixo.addItem("Eixo frontal");
            comboEixo.addItem("Eixo traseiro");

        } else {
            for (int i = 1; i <= t.getNumeroEixos(); i++) {
                comboEixo.addItem("Eixo " + String.valueOf(i));
            }
        }

        comboEixo.addItem("Estepe");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCodPneu = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        lposicao = new javax.swing.JLabel();
        comboPosicao = new javax.swing.JComboBox();
        tfCodPneu = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        labelEixo = new javax.swing.JLabel();
        comboEixo = new javax.swing.JComboBox();

        setTitle("Incluir Pneu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lCodPneu.setText("Codigo Pneu:");

        lEstado.setText("Estado:");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "1 Ressolagem", "2 Ressolagem", "3 Ressolagem" }));
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });
        comboEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboEstadoKeyPressed(evt);
            }
        });

        lposicao.setText("Posição:");

        comboPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPosicaoActionPerformed(evt);
            }
        });
        comboPosicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboPosicaoKeyPressed(evt);
            }
        });

        tfCodPneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodPneuActionPerformed(evt);
            }
        });
        tfCodPneu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodPneuKeyPressed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });

        labelEixo.setText("Eixo:");
        labelEixo.setToolTipText("");

        comboEixo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEixoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCodPneu)
                    .addComponent(lEstado)
                    .addComponent(lposicao)
                    .addComponent(labelEixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPosicao, 0, 158, Short.MAX_VALUE)
                    .addComponent(comboEixo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCodPneu))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodPneu)
                    .addComponent(tfCodPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEixo)
                    .addComponent(comboEixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lposicao)
                    .addComponent(comboPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void tfCodPneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodPneuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodPneuActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        incluiPneu();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void incluiPneu() {

        if (!tfCodPneu.getText().isEmpty()) {
            if (contemDuplicados(tfCodPneu.getText())) {
                JOptionPane.showMessageDialog(this, "Este código já existe, favor alterar!");
                return;
            }

            if (validatePosicao((String) comboPosicao.getSelectedItem(), (String) comboEixo.getSelectedItem())) {
                JOptionPane.showMessageDialog(this, "Está posição já foi selecionada, favor selecionar uma nova posição !");
                return;
            }

            if (selectedPosEqualsZero()) {
                JOptionPane.showMessageDialog(this, "Favor selecionar uma posição para o Pneu");
                return;
            }

            if (comboEixo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Favor selecionar um eixo");
            }

            Pneu pneu = new Pneu();
            pneu.setCodigo(tfCodPneu.getText());
            pneu.setPosicao((String) comboPosicao.getSelectedItem());
            pneu.setEstado((String) comboEstado.getSelectedItem());
            pneu.setEixo((String) comboEixo.getSelectedItem());
        	f.insertPneuInTable(pneu);
            f.getComboTipo().setEnabled(false);
            JOptionPane.showMessageDialog(this, "Pneu incluso com sucesso !");
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Insira o código do pneu antes de confirmar !");
        }

    }

    private boolean selectedPosEqualsZero() {
        return comboPosicao.getSelectedIndex() == 0;
    }

    private boolean validatePosicao(String pos, String eixo) {
        for (Pneu p : f.getListPneu()) {
            if (p.getPosicao().equals(pos) && p.getEixo().equals(eixo)) {
                return true;
            }
        }
        return false;
    }

    private boolean contemDuplicados(String cod) {
        return existeCodigoNaLista(cod) || existeCodigoNaBase(cod);
    }

    private boolean existeCodigoNaBase(String cod) {
        List<Pneu> list = Database.selectAllPneuByCod(cod);
        for (Pneu p : list) {
            if (p.getCodigo().equals(cod)) {
                return true;
            }
        }
        return false;
    }

    private boolean existeCodigoNaLista(String cod) {
        for (Pneu p : f.getListPneu()) {
            if (p.getCodigo().equals(cod)) {
                return true;
            }
        }
        return false;
    }


    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluiPneu();
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluiPneu();
        }
    }//GEN-LAST:event_formKeyPressed

    private void tfCodPneuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodPneuKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluiPneu();
        }
    }//GEN-LAST:event_tfCodPneuKeyPressed

    private void comboPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPosicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPosicaoActionPerformed

    private void comboPosicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboPosicaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluiPneu();
        }
    }//GEN-LAST:event_comboPosicaoKeyPressed

    private void comboEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboEstadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluiPneu();
        }
    }//GEN-LAST:event_comboEstadoKeyPressed

    private void comboEixoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEixoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (comboEixo.getSelectedIndex() != 0) {
                comboPosicao.setEnabled(true);
            } else {
                comboPosicao.setEnabled(false);
            }
            
            if(((String)comboEixo.getSelectedItem()).equals("Estepe")){
                comboPosicao.setSelectedIndex(comboPosicao.getItemCount() -1);
                comboPosicao.setEnabled(false);
            }
                

        }
    }//GEN-LAST:event_comboEixoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PneuForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PneuForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PneuForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PneuForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PneuForm(f).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox comboEixo;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JComboBox comboPosicao;
    private javax.swing.JLabel lCodPneu;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel labelEixo;
    private javax.swing.JLabel lposicao;
    private javax.swing.JTextField tfCodPneu;
    // End of variables declaration//GEN-END:variables
}
